package manajemen.barang.pusaka;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class MainFrame extends javax.swing.JFrame {
    Connection con ;
    PreparedStatement pst;
    ResultSet RS;
    Date date = new Date();
    java.sql.Date sqldate = new java.sql.Date(date.getTime());
   
    
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(this);
        konek();
        loadPemasukan();
        loadpengeluaran();
        txtfieldmerk.setHorizontalAlignment(JTextField.CENTER);
        txttanggal.setHorizontalAlignment(JTextField.CENTER);
        
        this.txtnamabarang.setBorder(BorderFactory.createCompoundBorder(
        this.txtnamabarang.getBorder(),BorderFactory.createEmptyBorder(0,5,0,0)));
        
        this.txtstok.setBorder(BorderFactory.createCompoundBorder(
        this.txtstok.getBorder(),BorderFactory.createEmptyBorder(0,5,0,0)));
        
        this.txtfieldharga.setBorder(BorderFactory.createCompoundBorder(
        this.txtfieldharga.getBorder(),BorderFactory.createEmptyBorder(0,5,0,0)));
        

    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        delbtn = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        aboutbtn = new javax.swing.JButton();
        mainpanel = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Addpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        txtmerk = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        viewbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addpenjualanbtn = new javax.swing.JButton();
        addpemasukanbtn = new javax.swing.JButton();
        tambahkanbtn = new javax.swing.JButton();
        delpanel = new javax.swing.JPanel();
        viewpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pemasukanbtn = new javax.swing.JButton();
        pengeluaranbtn = new javax.swing.JButton();
        gantibtn = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();
        PanelPemasukan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePemasukan = new javax.swing.JTable();
        backpemasukan = new javax.swing.JButton();
        PanelPengeluaran = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePengeluaran = new javax.swing.JTable();
        backpengeluaran = new javax.swing.JButton();
        aboutpanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        addpemasukan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfieldharga = new javax.swing.JTextField();
        cbox = new javax.swing.JComboBox<>();
        txtstok = new javax.swing.JTextField();
        lbharga = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtnamabarang = new javax.swing.JTextField();
        lbstok = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        findbtn = new javax.swing.JButton();
        txttanggal = new javax.swing.JTextField();
        lbtanggal = new javax.swing.JLabel();
        lbmerk = new javax.swing.JLabel();
        txtfieldmerk = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        addpengeluaran = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 980));

        sidepanel.setBackground(new java.awt.Color(0, 204, 255));
        sidepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        delbtn.setText("Delete");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        homebtn.setText("Home");
        homebtn.setBorder(null);
        homebtn.setBorderPainted(false);
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        aboutbtn.setText("Kasir");
        aboutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aboutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aboutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        mainpanel.setBackground(new java.awt.Color(0, 204, 255));
        mainpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        mainpanel.setLayout(new java.awt.CardLayout());

        HomePanel.setBackground(new java.awt.Color(0, 204, 255));

        jLabel9.setFont(new java.awt.Font("SansSerif", 3, 48)); // NOI18N
        jLabel9.setText("Selamat Datang di Pusaka HIMATIF");

        jLabel10.setFont(new java.awt.Font("SansSerif", 3, 48)); // NOI18N
        jLabel10.setText("Selamat Bekerja");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(531, Short.MAX_VALUE))
        );

        mainpanel.add(HomePanel, "card7");

        Addpanel.setBackground(new java.awt.Color(0, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Harga");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Jumlah");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Merk");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Nama");

        txtnama.setBorder(null);
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtjumlah.setBorder(null);

        txtmerk.setBorder(null);

        txtharga.setBorder(null);

        viewbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Note :   ID barang otomatis Dibuat, Untuk melihat ID barang");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Silahkan Tap \"View\" untuk masuk ke database");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tambah Barang");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        addpenjualanbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addpenjualanbtn.setText("add Pengeluaran");
        addpenjualanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpenjualanbtnActionPerformed(evt);
            }
        });

        addpemasukanbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addpemasukanbtn.setText("Add Pemasukan");
        addpemasukanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpemasukanbtnActionPerformed(evt);
            }
        });

        tambahkanbtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tambahkanbtn.setText("Tambahkan");
        tambahkanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkanbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddpanelLayout = new javax.swing.GroupLayout(Addpanel);
        Addpanel.setLayout(AddpanelLayout);
        AddpanelLayout.setHorizontalGroup(
            AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddpanelLayout.createSequentialGroup()
                .addGroup(AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddpanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(AddpanelLayout.createSequentialGroup()
                                .addGroup(AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmerk, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(tambahkanbtn))
                                .addGap(173, 173, 173)
                                .addGroup(AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(AddpanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel7))
                    .addGroup(AddpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(364, Short.MAX_VALUE))
            .addGroup(AddpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addpenjualanbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addpemasukanbtn)
                .addGap(15, 15, 15))
        );
        AddpanelLayout.setVerticalGroup(
            AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmerk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(tambahkanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddpanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddpanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(AddpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addpemasukanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addpenjualanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        mainpanel.add(Addpanel, "card3");

        delpanel.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout delpanelLayout = new javax.swing.GroupLayout(delpanel);
        delpanel.setLayout(delpanelLayout);
        delpanelLayout.setHorizontalGroup(
            delpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1033, Short.MAX_VALUE)
        );
        delpanelLayout.setVerticalGroup(
            delpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );

        mainpanel.add(delpanel, "card2");

        viewpanel.setBackground(new java.awt.Color(0, 204, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Stok", "Harga", "Merk"
            }
        ));
        jScrollPane1.setViewportView(table);

        pemasukanbtn.setText("Data Pemasukan");
        pemasukanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemasukanbtnActionPerformed(evt);
            }
        });

        pengeluaranbtn.setText("Data Pengeluaran");
        pengeluaranbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengeluaranbtnActionPerformed(evt);
            }
        });

        gantibtn.setText("Edit");
        gantibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gantibtnActionPerformed(evt);
            }
        });

        hapusbtn.setText("Hapus");
        hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewpanelLayout = new javax.swing.GroupLayout(viewpanel);
        viewpanel.setLayout(viewpanelLayout);
        viewpanelLayout.setHorizontalGroup(
            viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
                    .addGroup(viewpanelLayout.createSequentialGroup()
                        .addComponent(gantibtn)
                        .addGap(18, 18, 18)
                        .addComponent(hapusbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pengeluaranbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pemasukanbtn)))
                .addContainerGap())
        );
        viewpanelLayout.setVerticalGroup(
            viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(viewpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pengeluaranbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gantibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hapusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pemasukanbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        mainpanel.add(viewpanel, "card4");

        PanelPemasukan.setBackground(new java.awt.Color(0, 204, 255));

        tablePemasukan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablePemasukan);

        backpemasukan.setText("Back");
        backpemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backpemasukanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPemasukanLayout = new javax.swing.GroupLayout(PanelPemasukan);
        PanelPemasukan.setLayout(PanelPemasukanLayout);
        PanelPemasukanLayout.setHorizontalGroup(
            PanelPemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPemasukanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPemasukanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelPemasukanLayout.setVerticalGroup(
            PanelPemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPemasukanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainpanel.add(PanelPemasukan, "card5");

        PanelPengeluaran.setBackground(new java.awt.Color(0, 204, 255));

        tablePengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablePengeluaran);

        backpengeluaran.setText("Back");
        backpengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backpengeluaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPengeluaranLayout = new javax.swing.GroupLayout(PanelPengeluaran);
        PanelPengeluaran.setLayout(PanelPengeluaranLayout);
        PanelPengeluaranLayout.setHorizontalGroup(
            PanelPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPengeluaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPengeluaranLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backpengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelPengeluaranLayout.setVerticalGroup(
            PanelPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPengeluaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backpengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainpanel.add(PanelPengeluaran, "card6");

        aboutpanel.setBackground(new java.awt.Color(0, 204, 255));

        jLabel11.setText("Developer : Al-ibhaam");

        javax.swing.GroupLayout aboutpanelLayout = new javax.swing.GroupLayout(aboutpanel);
        aboutpanel.setLayout(aboutpanelLayout);
        aboutpanelLayout.setHorizontalGroup(
            aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutpanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addContainerGap(898, Short.MAX_VALUE))
        );
        aboutpanelLayout.setVerticalGroup(
            aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutpanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addContainerGap(669, Short.MAX_VALUE))
        );

        mainpanel.add(aboutpanel, "card8");

        addpemasukan.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Pilih ID Barang");

        txtfieldharga.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtfieldharga.setBorder(null);

        cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxActionPerformed(evt);
            }
        });

        txtstok.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtstok.setBorder(null);
        txtstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstokActionPerformed(evt);
            }
        });

        lbharga.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbharga.setText("Harga/Pcs");

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel14.setText("Nama Barang");

        txtnamabarang.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtnamabarang.setText(" ");
        txtnamabarang.setBorder(null);
        txtnamabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamabarangActionPerformed(evt);
            }
        });

        lbstok.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbstok.setText("Jumlah");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tambah Data Pemasukan");

        findbtn.setText("Tambahkan");
        findbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbtnActionPerformed(evt);
            }
        });

        txttanggal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txttanggal.setBorder(null);
        txttanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttanggalActionPerformed(evt);
            }
        });

        lbtanggal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbtanggal.setText("Tanggal");

        lbmerk.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbmerk.setText("Total");

        txtfieldmerk.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        txtfieldmerk.setBorder(null);
        txtfieldmerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldmerkActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel19.setText("Note : Total dan tanggal akan dicatat otomatis oleh system dan langsung masuk ke databases");

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel20.setText("Pastikan Untuk melakukan pencatatan di dalam jam Kerja Pusaka !");

        javax.swing.GroupLayout addpemasukanLayout = new javax.swing.GroupLayout(addpemasukan);
        addpemasukan.setLayout(addpemasukanLayout);
        addpemasukanLayout.setHorizontalGroup(
            addpemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpemasukanLayout.createSequentialGroup()
                .addGroup(addpemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addpemasukanLayout.createSequentialGroup()
                        .addGroup(addpemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addpemasukanLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(addpemasukanLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(findbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(addpemasukanLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(addpemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addpemasukanLayout.createSequentialGroup()
                        .addGroup(addpemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addpemasukanLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(lbmerk, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addpemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtnamabarang, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtstok, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtfieldmerk, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtfieldharga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                .addComponent(lbstok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbharga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addpemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(553, 553, 553))
                    .addGroup(addpemasukanLayout.createSequentialGroup()
                        .addGroup(addpemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(lbtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        addpemasukanLayout.setVerticalGroup(
            addpemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpemasukanLayout.createSequentialGroup()
                .addGroup(addpemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addpemasukanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addpemasukanLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(addpemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addpemasukanLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addpemasukanLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbstok)))
                .addGap(1, 1, 1)
                .addComponent(txtstok, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lbharga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfieldharga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addpemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbmerk, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addpemasukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfieldmerk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(findbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainpanel.add(addpemasukan, "card9");

        jLabel12.setText("add pengeluaran");

        javax.swing.GroupLayout addpengeluaranLayout = new javax.swing.GroupLayout(addpengeluaran);
        addpengeluaran.setLayout(addpengeluaranLayout);
        addpengeluaranLayout.setHorizontalGroup(
            addpengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpengeluaranLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel12)
                .addContainerGap(712, Short.MAX_VALUE))
        );
        addpengeluaranLayout.setVerticalGroup(
            addpengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpengeluaranLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel12)
                .addContainerGap(613, Short.MAX_VALUE))
        );

        mainpanel.add(addpengeluaran, "card10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // panel adding
        mainpanel.add(Addpanel);
        mainpanel.repaint();
        mainpanel.revalidate();       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // panel adding
        mainpanel.add(delpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_delbtnActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // panel adding
        mainpanel.add(viewpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
        load(); 
    }//GEN-LAST:event_viewbtnActionPerformed

    private void addpemasukanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpemasukanbtnActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // panel adding
        mainpanel.add(addpemasukan);
        mainpanel.repaint();
        mainpanel.revalidate();
        loadcbox();
        txttanggal.setEditable(false);
        txtfieldmerk.setEditable(false);
        
        
    }//GEN-LAST:event_addpemasukanbtnActionPerformed

    private void pemasukanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemasukanbtnActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // panel adding
        mainpanel.add(PanelPemasukan);
        mainpanel.repaint();
        mainpanel.revalidate();
        
    }//GEN-LAST:event_pemasukanbtnActionPerformed

    private void pengeluaranbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengeluaranbtnActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // panel adding
        mainpanel.add(PanelPengeluaran);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_pengeluaranbtnActionPerformed

    private void backpemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backpemasukanActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // panel adding
        mainpanel.add(viewpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_backpemasukanActionPerformed

    private void backpengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backpengeluaranActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // panel adding
        mainpanel.add(viewpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_backpengeluaranActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // panel adding
        mainpanel.add(HomePanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_homebtnActionPerformed

    private void aboutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutbtnActionPerformed

        
        
        
        
    }//GEN-LAST:event_aboutbtnActionPerformed

    private void gantibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gantibtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gantibtnActionPerformed

    private void hapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusbtnActionPerformed

    private void addpenjualanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpenjualanbtnActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // panel adding
        mainpanel.add(addpengeluaran);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_addpenjualanbtnActionPerformed

    private void cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxActionPerformed
        String cb = cbox.getSelectedItem().toString();
        try {
            String sqlcbox = "select * from list_barang where id_barang = ?";
            PreparedStatement PST = con.prepareStatement(sqlcbox);
            PST.setString(1,(String)cbox.getSelectedItem());
            ResultSet res = PST.executeQuery();
            while(res.next()){
                txtnamabarang.setText(res.getString("nama_barang"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboxActionPerformed

    private void tambahkanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkanbtnActionPerformed

        if ("".equals(txtnama.getText()) && "".equals(txtjumlah.getText()) && "".equals(txtharga.getText()) && "".equals(txtmerk.getText())) {
                    JOptionPane.showMessageDialog(this,
                    "Data Tidak Boleh Kosong",
                    "Alert",
                    JOptionPane.WARNING_MESSAGE); 
        }
        else{
             int jawab = JOptionPane.showOptionDialog(this, 
                    "Pastikan Data Yang di Inputkan Sudah Sesuai ?", 
                    "Alert", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);   
     if(jawab == JOptionPane.YES_OPTION){
        JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
       
        // code input Data Here // 
        try {
            String nama = txtnama.getText();
            String jumlah = txtjumlah.getText();
            String harga = txtharga.getText();
            String merk = txtmerk.getText();
            pst = con.prepareStatement("INSERT INTO list_barang (id_barang, nama_barang, jumlah_stok, harga_barang, merk) VALUES (null, ?, ?, ?, ?)");
            pst.setString(1,nama);
            pst.setString(2,jumlah);
            pst.setString(3,harga);
            pst.setString(4,merk);
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }            
        }
    }//GEN-LAST:event_tambahkanbtnActionPerformed

    private void txtnamabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamabarangActionPerformed

    private void txtstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstokActionPerformed

    private void findbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbtnActionPerformed

             int jawab = JOptionPane.showOptionDialog(this, 
                    "Ingin menambahkan Data Dengan ID = "+cbox.getSelectedItem().toString()+" ( "+txtnamabarang.getText()+" )", 
                    "Alert", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null); 
             if(jawab == JOptionPane.YES_OPTION){
    try {
            String idbarang = cbox.getSelectedItem().toString();
            String jumlahjual = txtstok.getText();
            String harga = txtfieldharga.getText();
            pst = con.prepareStatement("INSERT INTO table_pemasukan (id_pemasukan, id_barang_terjual, jumlah_terjual, harga_jual_barang, total, tanggal_pemasukan) VALUES (null, ?, ?, ?, null, ?)");
            pst.setString(1, idbarang);
            pst.setString(2,jumlahjual);
            pst.setString(3,harga);
            pst.setDate(4,sqldate);
            pst.executeUpdate();
       JOptionPane.showMessageDialog(this,
                    "Data Masuk",
                    "Alert",
                    JOptionPane.INFORMATION_MESSAGE); 
            
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    try {
            String sql = "select * from table_pemasukan ORDER BY id_pemasukan DESC LIMIT 1;";
            PreparedStatement PST = con.prepareStatement(sql);
            ResultSet res = PST.executeQuery();
            while(res.next()){
                txtfieldmerk.setText(res.getString("total"));
                txttanggal.setText(res.getString("tanggal_pemasukan"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
             }
             
                
                
    }//GEN-LAST:event_findbtnActionPerformed

    private void txttanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttanggalActionPerformed

    private void txtfieldmerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldmerkActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtfieldmerkActionPerformed
      static final String linkDB = "jdbc:mysql://localhost:3306/produk_pusaka";
      static final String user = "root";
      static final String pass = "";
    public void konek(){
                try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection(linkDB,user,pass);
            } catch (SQLException ex) {
                Logger.getLogger(testTable.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(testTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void load(){
      DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NAMA BARANG");
        model.addColumn("STOK");
        model.addColumn("HARGA");
        model.addColumn("MERK");
        try {
            String sql = "select * from list_barang";
            Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
                table.setModel(model);
            }
        } catch (SQLException e) {
            System.out.println("ERROR : " + e.getMessage());
        }
    }
    public void loadPemasukan(){
              DefaultTableModel model1 = new DefaultTableModel();
        model1.addColumn("ID Pemasukan");
        model1.addColumn("ID barang");
        model1.addColumn("Jumlah");
        model1.addColumn("HARGA jual");
        model1.addColumn("Total");
        model1.addColumn("Tanggal");
        try {
            int no = 1;
            String sql = "select * from table_pemasukan";
            Statement pst = con.createStatement();
            java.sql.ResultSet rs = pst.executeQuery(sql);
            while (rs.next()) {
                model1.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),rs.getString(6)});
                tablePemasukan.setModel(model1);
            }
        } catch (SQLException e) {
            System.out.println("ERROR : " + e.getMessage());
        }
    }
    public void loadpengeluaran(){
                      DefaultTableModel model2 = new DefaultTableModel();
        model2.addColumn("ID Belanja");
        model2.addColumn("ID barang");
        model2.addColumn("Jumlah Beli");
        model2.addColumn("Harga Beli");
        model2.addColumn("Total");
        model2.addColumn("Suplier");
        model2.addColumn("Tanggal");
        try {
            int no = 1;
            String sql = "select * from table_belanja";
            Statement pst = con.createStatement();
            java.sql.ResultSet rs = pst.executeQuery(sql);
            while (rs.next()) {
                model2.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),rs.getString(6),rs.getString(7)});
                tablePengeluaran.setModel(model2);
            }
        } catch (SQLException e) {
            System.out.println("ERROR : " + e.getMessage());
        }
    }
    public void loadcbox(){
        String query = "select * from list_barang";
        try{
            pst = con.prepareStatement (query);
            RS = pst.executeQuery();
            while(RS.next()){
                cbox.addItem(RS.getString("id_barang"));
            }
        }catch(Exception e ){
            
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Addpanel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel PanelPemasukan;
    private javax.swing.JPanel PanelPengeluaran;
    private javax.swing.JButton aboutbtn;
    private javax.swing.JPanel aboutpanel;
    private javax.swing.JPanel addpemasukan;
    private javax.swing.JButton addpemasukanbtn;
    private javax.swing.JPanel addpengeluaran;
    private javax.swing.JButton addpenjualanbtn;
    private javax.swing.JButton backpemasukan;
    private javax.swing.JButton backpengeluaran;
    private javax.swing.JComboBox<String> cbox;
    private javax.swing.JButton delbtn;
    private javax.swing.JPanel delpanel;
    private javax.swing.JButton findbtn;
    private javax.swing.JButton gantibtn;
    private javax.swing.JButton hapusbtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbharga;
    private javax.swing.JLabel lbmerk;
    private javax.swing.JLabel lbstok;
    private javax.swing.JLabel lbtanggal;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JButton pemasukanbtn;
    private javax.swing.JButton pengeluaranbtn;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JTable table;
    private javax.swing.JTable tablePemasukan;
    private javax.swing.JTable tablePengeluaran;
    private javax.swing.JButton tambahkanbtn;
    private javax.swing.JTextField txtfieldharga;
    private javax.swing.JTextField txtfieldmerk;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtmerk;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtstok;
    private javax.swing.JTextField txttanggal;
    private javax.swing.JButton viewbtn;
    private javax.swing.JPanel viewpanel;
    // End of variables declaration//GEN-END:variables
}
